// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FractalView
{
	public partial class AboutProgramViewController : NSViewController
	{
		public AboutProgramViewController (IntPtr handle) : base (handle)
		{
		}

        partial void BackButtonClick(NSObject sender)
        {
            DismissViewController(this);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }
    }
}
