// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;
using FractalViewMac.Model;
using FractalViewMac.Model.Common.Classes;
using FractalViewMac.Model.Common.Enums;
using FractalViewMac.Model.Fractals;
using SkiaSharp;
using SkiaSharp.Views.Mac;

namespace FractalView
{
    public partial class FractalTypeViewController : NSViewController
	{
        AbstractFractal fractalData = MainClass.mainViewController.fractalData;

		public FractalTypeViewController (IntPtr handle) : base (handle)
		{
		}

        void UpdateFractalInfo() 
        {
            CenterXLabel.StringValue = $"       Центр X: {fractalData.CenterX}";
            CenterYLabel.StringValue = $"       Центр Y: {fractalData.CenterY}";
            SizeAreaLabel.StringValue = $"Увеличение: {fractalData.SizeArea}";
        }

        async void CreateFractalPresentation(AbstractFractal f)
        {
            AbstractFractal fractal = f.Clone() as AbstractFractal;
            fractal.Reset();

            GenerationSettings generationSettings = new GenerationSettings()
            {
                IterationCount = 500,
                Algorithm = GenerationAlgorithms.MultiThreadCalculation,
                Height = (int)FractalPresenterImageView.Frame.Size.Height,
                Width = (int)FractalPresenterImageView.Frame.Size.Width
            };

            ColorSettings colorSettings = new ColorSettings();

            FractalCreator presentImageCreator = new FractalCreator(fractal, generationSettings, colorSettings);

            SKBitmap bmp = await presentImageCreator.CreateAsync();

            FractalPresenterImageView.Image = bmp.ToNSImage();

        }

        partial void OkButtonClick(NSObject sender)
        {
            switch (FractalTypeComboBox.SelectedIndex)
            {
                case 0:
                    MainClass.mainViewController.fractalData = new FractalMandelbrot();
                    MainClass.mainViewController.creator = new FractalCreator(MainClass.mainViewController.fractalData, 
                                                                              MainClass.mainViewController.genSettings, 
                                                                              MainClass.mainViewController.clrSettings);
                    break;
                case 1:
                    MainClass.mainViewController.fractalData = new FractalJulia();
                    MainClass.mainViewController.creator = new FractalCreator(MainClass.mainViewController.fractalData,
                                                                              MainClass.mainViewController.genSettings,
                                                                              MainClass.mainViewController.clrSettings);
                    break;
                case 2:
                    MainClass.mainViewController.fractalData = new FractalLambda();
                    MainClass.mainViewController.creator = new FractalCreator(MainClass.mainViewController.fractalData,
                                                                              MainClass.mainViewController.genSettings,
                                                                              MainClass.mainViewController.clrSettings);
                    break;
                default:
                    throw new NotImplementedException();

            }

            MainClass.mainViewController.Reset();
            DismissViewController(this);
        }

        partial void CancelButtonClick(NSObject sender)
        {
            DismissViewController(this);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            UpdateFractalInfo();

            CreateFractalPresentation(MainClass.mainViewController.fractalData);

            switch(fractalData.FractalType)
            {
                case "Mandelbrot":
                    FractalTypeComboBox.SelectItem(0);
                    break;
                case "Julia":
                    FractalTypeComboBox.SelectItem(1);
                    break;
                case "Lambda":
                    FractalTypeComboBox.SelectItem(2);
                    break;
                default:
                    throw new NotImplementedException();
            }
        }
    }
}
